title: Welcome to Manali's Portfolio !
logo: 
![PSX_20210825_214051 (2)](https://github.com/Manali1608/portfolio/assets/85641970/c56b7f07-4f5e-4e1f-96ec-1b3941d9e3ca)
description: I am a Data Analyst with excellent problem solving skills armed with the knowledge of Excel, SQL, Power BI, Tableau.I am passionate about diving deep into data to extract meaningful information, visualize and present data so that others can easily make sense of it.
#description: Minimal is a theme for GitHub Pages.
#show_downloads: true
theme: jekyll-theme-minimal

