title: Welcome to Manali's Portfolio
description:I am a Data Analyst with excellent problem solving skills armed with the knowledge of Excel, SQL, Power BI, Tableau.
I am passionate about diving deep into data to extract meaningful information, visualize and present data so that others can easily make sense of it.
#logo: /assets/img/logo.png
#description: Minimal is a theme for GitHub Pages.
#show_downloads: true
theme: jekyll-theme-minimal
